name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.3-snapshot-2026-03-05"
          skip-verify-signature: true

      - name: Install Swift SDK for WebAssembly
        run: swift sdk install https://download.swift.org/swift-6.3-branch/wasm-sdk/swift-6.3-DEVELOPMENT-SNAPSHOT-2026-03-05-a/swift-6.3-DEVELOPMENT-SNAPSHOT-2026-03-05-a_wasm.artifactbundle.tar.gz --checksum fb8744a343c02277d3f695a524b9ddc3fee18b96396282a84f7fcf875602bdc6

      - name: Install dependencies
        run: swift package resolve --package-path swift && pnpm install

      - name: Install wasm-opt
        uses: phi-ag/setup-binaryen@v1
        with:
          version: "125"

      - name: Build VitePress site
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.54.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # packageManager: pnpm
